#!/bin/bash
set -e

# we must use stderr for error messages
if [[ -z "${PIVNET_TOKEN}" ]]; then
  >&2 echo "PIVNET_TOKEN environment variable is required"
  exit 1
fi

pivnet login --api-token ${PIVNET_TOKEN} > /dev/null
pivnet products --format=json
